"""Add content_type to Card

Revision ID: f8665a62be73
Revises: ae29b07738e3
Create Date: 2026-09-09 21:28:36.295349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8665a62be73'
down_revision: Union[str, Sequence[str], None] = 'ae29b07738e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('content_type', sa.String(length=32), nullable=False, server_default='NEWS'))
    op.add_column('sources', sa.Column('district', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'content_type')
    op.drop_column('sources', 'district')
    # ### end Alembic commands ###
